create table sub_allocation(`id` int(11) NOT NULL AUTO_INCREMENT,
`employee_id` int(11) DEFAULT NULL,
`depart_id` int(11) DEFAULT NULL,
`course_id` int(11) DEFAULT NULL,
`batch_id` int(11) DEFAULT NULL,
`subject_id` int(11) DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `fk_courses` (`course_id`),
KEY `fk_batch` (`batch_id`),
KEY `fk_subject` (`subject_id`), 
KEY `fk_employee` (`employee_id`),
KEY `fk_depar` (`depart_id `),
CONSTRAINT `fk_batch` FOREIGN KEY (`batch_id`) REFERENCES `batch` (`id`),
CONSTRAINT `fk_batch` FOREIGN KEY (`batch_id`) REFERENCES `batch` (`id`),
CONSTRAINT `fk_subject` FOREIGN KEY (`subject_id`) REFERENCES `subject` (`id`),
CONSTRAINT `fk_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`id`),
CONSTRAINT `fk_depar` FOREIGN KEY (`depart_id `) REFERENCES `department` (`id`));
